### PR TITLE
Moved web.d.ts in /src folder to fix import in Index.d.ts

### PR DESCRIPTION
**Pull request by Aekk0**

### CODE REVIEW

**Comment by tony-go** [comment]
Hey @Aekk0 👋 

Thanks for submitting a pull request 🙌 

Could you please fill the description with:
- a bit of context
- what is the output of the PR

Cheers ^^

**Comment by Aekk0** [comment]
Hey @tony-go 

- The export in `index.d.ts` is wrong since `web.d.ts` isn't in the `src` folder but at the root of the project. Instead of changing this line of export, It came to me that it was more logical to move the `web.d.ts` file into the `src` folder as others types are exported in it.
- Fixing the error from `@nodesecure/scanner` related to the export of types definitions as shown below.

image

**Comment by tony-go** [comment]
Hey @Aekk0 👋 

Thanks for providing these details.

I experienced the same yesterday: https://github.com/NodeSecure/preview/pull/28/files

I had a chat with @fraxken, and it seems that it's volunteered to make the lib compatible with nodejs and browsers.

So I think that `import { FlagObject } from "@nodesecure/flags/web"` will be the new way to go.

**Comment by fraxken** [comment]
@tony-go I don't think it was the same problem.

I discussed the subject this morning with @Rossb0b on discord. The `web.d.ts` was at the root because of an issue with TypeScript being not able to read the `exports` field in the package.json (So it was not providing intellisense in VSCode).

For context I had a discussion in french in the community:
image

https://github.com/microsoft/TypeScript/issues/33079

Maybe this has been resolved in recent version of TS (this need to be tested).

**Comment by tony-go** [comment]
Thanks for your answer @fraxken 👍 

Could you test with a different version of ts and tell us if it fixes the bug? @Aekk0?

**Comment by fraxken** [comment]
Closing for inactivity

**Pull request closed without merging**
